/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenComplaintsRouteImport } from './routes/citizen.complaints'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenForgotPasswordRouteImport } from './routes/citizen.forgot-password'
import { Route as CitizenLoginRouteImport } from './routes/citizen.login'
import { Route as CitizenRegisterRouteImport } from './routes/citizen.register'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerComplaintsRouteImport } from './routes/officer.complaints'
import { Route as OfficerDashboardRouteImport } from './routes/officer.dashboard'
import { Route as OfficerLoginRouteImport } from './routes/officer.login'
import { Route as OfficerProfileRouteImport } from './routes/officer.profile'
import { Route as OfficerRegisterRouteImport } from './routes/officer.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenComplaintsRoute = CitizenComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenForgotPasswordRoute = CitizenForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenLoginRoute = CitizenLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenRegisterRoute = CitizenRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerComplaintsRoute = OfficerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerRegisterRoute = OfficerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => OfficerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/forgot-password': typeof CitizenForgotPasswordRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/register': typeof OfficerRegisterRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/forgot-password': typeof CitizenForgotPasswordRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/register': typeof OfficerRegisterRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/citizen/complaints': typeof CitizenComplaintsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/forgot-password': typeof CitizenForgotPasswordRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/login': typeof OfficerLoginRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/register': typeof OfficerRegisterRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/officer'
    | '/citizen/complaints'
    | '/citizen/dashboard'
    | '/citizen/forgot-password'
    | '/citizen/login'
    | '/citizen/register'
    | '/citizen/report'
    | '/officer/complaints'
    | '/officer/dashboard'
    | '/officer/login'
    | '/officer/profile'
    | '/officer/register'
    | '/citizen/'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen/complaints'
    | '/citizen/dashboard'
    | '/citizen/forgot-password'
    | '/citizen/login'
    | '/citizen/register'
    | '/citizen/report'
    | '/officer/complaints'
    | '/officer/dashboard'
    | '/officer/login'
    | '/officer/profile'
    | '/officer/register'
    | '/citizen'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/officer'
    | '/citizen/complaints'
    | '/citizen/dashboard'
    | '/citizen/forgot-password'
    | '/citizen/login'
    | '/citizen/register'
    | '/citizen/report'
    | '/officer/complaints'
    | '/officer/dashboard'
    | '/officer/login'
    | '/officer/profile'
    | '/officer/register'
    | '/citizen/'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/complaints': {
      id: '/citizen/complaints'
      path: '/complaints'
      fullPath: '/citizen/complaints'
      preLoaderRoute: typeof CitizenComplaintsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/forgot-password': {
      id: '/citizen/forgot-password'
      path: '/forgot-password'
      fullPath: '/citizen/forgot-password'
      preLoaderRoute: typeof CitizenForgotPasswordRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/login': {
      id: '/citizen/login'
      path: '/login'
      fullPath: '/citizen/login'
      preLoaderRoute: typeof CitizenLoginRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/register': {
      id: '/citizen/register'
      path: '/register'
      fullPath: '/citizen/register'
      preLoaderRoute: typeof CitizenRegisterRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/complaints': {
      id: '/officer/complaints'
      path: '/complaints'
      fullPath: '/officer/complaints'
      preLoaderRoute: typeof OfficerComplaintsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/login': {
      id: '/officer/login'
      path: '/login'
      fullPath: '/officer/login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/profile': {
      id: '/officer/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerProfileRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/register': {
      id: '/officer/register'
      path: '/register'
      fullPath: '/officer/register'
      preLoaderRoute: typeof OfficerRegisterRouteImport
      parentRoute: typeof OfficerRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenComplaintsRoute: typeof CitizenComplaintsRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenForgotPasswordRoute: typeof CitizenForgotPasswordRoute
  CitizenLoginRoute: typeof CitizenLoginRoute
  CitizenRegisterRoute: typeof CitizenRegisterRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenComplaintsRoute: CitizenComplaintsRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenForgotPasswordRoute: CitizenForgotPasswordRoute,
  CitizenLoginRoute: CitizenLoginRoute,
  CitizenRegisterRoute: CitizenRegisterRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface OfficerRouteChildren {
  OfficerComplaintsRoute: typeof OfficerComplaintsRoute
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerLoginRoute: typeof OfficerLoginRoute
  OfficerProfileRoute: typeof OfficerProfileRoute
  OfficerRegisterRoute: typeof OfficerRegisterRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerComplaintsRoute: OfficerComplaintsRoute,
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerLoginRoute: OfficerLoginRoute,
  OfficerProfileRoute: OfficerProfileRoute,
  OfficerRegisterRoute: OfficerRegisterRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
